name: Download NBA Game Notes

on:
  schedule:
    # Every 30 minutes, 24 hours a day
    - cron: "0,30 * * * *"
  workflow_dispatch:     # allow manual runs

permissions:
  contents: write   # allow pushing commits

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install R
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base

      - name: Run R script
        run: Rscript download_game_notes.R

      - name: Add timestamp file (forces a change)
        run: |
          date -u +"%Y-%m-%d %H:%M:%S UTC" > last_run.txt

      - name: Commit and push changes (always)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add nba_game_notes/* last_run.txt
          git commit -m "Update NBA game notes at $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
